# [secrets]
    # personal wifi
CIRCUITPY_WIFI_SSID = "PERSONAL WIFI NAME"
CIRCUITPY_WIFI_PASSWORD = "PERSONAL WIFI PASSWD"

    #adafruit creds (**optional**)
ADAFRUIT_IO_USERNAME = "USERNAME"
ADAFRUIT_IO_KEY = "API KEY"

    # spotify
CLIENT_ID = "CLIENT_ID FROM SPOTIFY DEV ACCOUNT"
CLIENT_SECRET = "CLIENT_SECRET FROM SPOTIFY DEV ACCOUNT"
REFRESH_TOKEN = "REFRESH TOKEN FROUND IN TERMINAL OUTPUT ON INITIAL RUN"

ACCESS_TOKEN = "" # **optional** new access token is gabbed each session 
VOLUME = 75

# [channel selection]
IS_SPOTIFY = 1
